### PR TITLE
New protocol and GUI

### PR DESCRIPTION
**Pull request by Marcin648**
Using COBS instead of simple self written protocol.
GUI using PyQt5.
Simple interface to add new games.

### CODE REVIEW

**Comment by albiekreef** [comment]
Hi there. I have come across your thread about the bmw e90 cluster. I have one laying around and want to use it for my new simulator project. I would like to know if it will be able to work on other games as well like dirt rally and project cars 2 etc. I am by no means a coder so I have to ask first....otherwise my cluster is worth nothing to me. I am not at all good with coding so I am asking for advice. Thank you very much.

**Comment by Marcin648** [comment]
> Hi there. I have come across your thread about the bmw e90 cluster. I have one laying around and want to use it for my new simulator project. I would like to know if it will be able to work on other games as well like dirt rally and project cars 2 etc. I am by no means a coder so I have to ask first....otherwise my cluster is worth nothing to me. I am not at all good with coding so I am asking for advice. Thank you very much.

I am going to add other games. Unfortunately, I am not able to say when I will find the time for it. February may be. For now, it supports ETS2 and ATS2. Maybe I will do a compatibility layer with simhub.

**Comment by albiekreef** [comment]
> > Hi there. I have come across your thread about the bmw e90 cluster. I have one laying around and want to use it for my new simulator project. I would like to know if it will be able to work on other games as well like dirt rally and project cars 2 etc. I am by no means a coder so I have to ask first....otherwise my cluster is worth nothing to me. I am not at all good with coding so I am asking for advice. Thank you very much.
> 
> I am going to add other games. Unfortunately, I am not able to say when I will find the time for it. February may be. For now, it supports ETS2 and ATS2. Maybe I will do a compatibility layer with simhub.

Oh okay that sounds really great. I really admire you guys that have the skills to do these things. I really hope you can somehow manage to do so and maybe share it, I know it sounds crap of me saying that as you deserve some sort of compensation for your work, but it really is amazing to download these things and it just works. I am not good with coding at all, but I am doing some projects regarding sim racing steering wheel setups. Currently building my first good sim rig and that is why I would like to use this cluster that I have. Thanks for the reply and I will be following the thread for sure. Hope you have a great new year ahead of you.

Regards
Albie

**Comment by Marcin648** [comment]
By the way. You don't need to buy Arduino Mega and CAN BUS shield. I got information from someone then this work also fine on cheap clone of Arduino UNO and cheap MCP2515 CAN Bus module :)

**Comment by albiekreef** [comment]
Awesome.....I already have an Uno laying around and the can bus moduls is
available in my town. I have a long way to go and coding is a nightmare for
me. But prototyping with my 3d printer is more my style. I really hope you
can get the time to do what you do. If you could make that work with
simhub....my friend that would be awesome. If you have a fee for it by then
I would not mind paying for it because it is your hard work in the end.

**Comment by albiekreef** [comment]
Awesome.....I already have an Uno laying around and the can bus module is
available in my town. I have a long way to go and coding is a nightmare for
me. But prototyping with my 3d printer is more my style. I really hope you
can get the time to do what you do. If you could make that work with
simhub....my friend that would be awesome.

**Comment by albiekreef** [comment]
Hi there sir. Hope you are well. I am just curious, have you had any time to see if you can add support for other games as well ? I am super excited about this project. Have all my parts except for the shield then I will test it out on ATS in the meantime. Hope to hear from you. Be safe

**Comment by Marcin648** [comment]
@albiekreef Hi!
Unfortunately, I still have limited access to my cluster. A few days ago I improved the precision of showing the speed. As for the games. Most likely I will do a new project that will work with SimHub. I still don't know how easy and possible it is.

**Comment by albiekreef** [comment]
Hi there....

Oh okay, all cool man, I am just excited about the possibilities of my project and since I am also trying to find my e90 cluster a forever simulator home. So I appreciate the response and everything. Sorry if I am a pain. Stay safe.

**Pull request merged**
